### ISSUE TITLE
helm.exe "helm" command generated instead of the correct one

### ISSUE THREAD

**Issue by jrouaix** [nuke-build/helm#5]
Hello Nuke.folks

I'm trying now to use Nuke as a release scripting tool and I think the generated command has a 'helm' word that is added : 

Code:
`HelmList();`

Generates :
'C:\...<somepathonmymchine>\_tools\helm.exe helm list'

And the error :
```
Error: unknown command "helm" for "helm"
Run 'helm --help' for usage.
Process 'helm.exe' exited with code 1. Verify the invocation.
```

I asume you tried to use the commands at least one time, so perhaps it's working with the bash version. 
I'll try the same on our worker servers (ubuntu) instead of my local windows.

thank you for the tool I hope as an early adopter I help you debug and the community will then get a better tool.

**Comment by arodus** [comment]
Thanks for raising this issue. 🎉
I just released a new version which fixes the issue.
